name: "Build and Push"
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven

      - name: Build image with Maven
        run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=distucker/spring-petclinic:${{ github.sha }}

      - name: Push Image to Docker Hub
        run: |
          docker push distucker/spring-petclinic:${{ github.sha }}
